// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Sub string `json:"subt"`
	Obj string `json:"obj"`
	Act string `json:"act"`
}

type Response struct {
	Message string `json:"message"`
}
