// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Sub string `json:"sub,optional"` //用户所属的角色
	Obj string `json:"obj,optional"` //用户需要查看机器人ID
	Act string `json:"act,optional"` //用户需要的动作，默认是read
}

type Response struct {
	Message string `json:"message"`
}
