// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	api "github.com/DemoLiang/casbin-demo/internal/handler/api"
	"github.com/DemoLiang/casbin-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hello",
				Handler: api.HelloHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
